services:

  db-container:
    image: mysql:8.0
    container_name: db-container
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: Test@1234
      MYSQL_DATABASE: signup_db

    ports:
      - "3306:3306"

    volumes:
      - signup-volume:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pTest@1234"]
      interval: 5s
      timeout: 5s
      retries: 20


  backend-container:
    build: ./backend
    container_name: backend-container
    restart: always

    ports:
      - "5000:5000"

    environment:
      DB_HOST: db-container
      DB_USER: root
      DB_PASS: Test@1234
      DB_NAME: signup_db

    volumes:
      - ./backend:/app
      - /app/node_modules

    command: sh -c "npm install && npm start"

    depends_on:
      db-container:
        condition: service_healthy


  frontend-container:
    build: ./frontend
    container_name: frontend-container
    restart: always

    ports:
      - "3000:3000"

    volumes:
      - ./frontend:/app
      - /app/node_modules

    command: sh -c "npm install && npm install react-scripts --save && npm start"

    depends_on:
      - backend-container


volumes:
  signup-volume:
